# Generated by Django 5.1.6 on 2026-02-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_carwash_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='moykalar/'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwashes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CarwashComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='carwash.carwash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwash_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarwashService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='carwash.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='CarwashRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='carwash.carwash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwash_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('carwash', 'user'), name='uniq_user_rating_per_carwash')],
            },
        ),
    ]
